#!/bin/bash

RESET_ALL='\e[0m'

BOLD='\e[1m'
FAINT='\e[2m'
ITALIC='\e[3m'
UNDERLINE='\e[4m'
SLOW_BLINK='\e[5m'
FAST_BLINK='\e[6m'
REVERSE='\e[7m'
CONCEAL='\e[8m'
STRIKEOUT='\e[9m'

BOLD_OFF='\e[21m'
FAINT_OFF='\e[22m'
ITALIC_OFF='\e[23m'
UNDERLINE_OFF='\e[24m'
BLINK_OFF='\e[25m'
REVERSE_OFF='\e[27m'
CONCEAL_OFF='\e[28m'
STRIKEOUT_OFF='\e[29m'

FG_BLACK='\e[30m'
FG_RED='\e[31m'
FG_GREEN='\e[32m'
FG_YELLOW='\e[33m'
FG_BLUE='\e[34m'
FG_MAGENTA='\e[35m'
FG_CYAN='\e[36m'
FG_WHITE='\e[37m'
FG_OFF='\e[39m'

BG_BLACK='\e[40m'
BG_RED='\e[41m'
BG_GREEN='\e[42m'
BG_YELLOW='\e[43m'
BG_BLUE='\e[44m'
BG_MAGENTA='\e[45m'
BG_CYAN='\e[46m'
BG_WHITE='\e[47m'
BG_OFF='\e[49m'

BC='\['
EC='\]'

function crush {
    : "$1"
    : "${_//\\\]\\\[}"
    : "${_//m\\e\[/;}"
    echo "$_"
}

P=''
P=$P$BC$FG_GREEN$EC'\u'$BC$FG_OFF$EC
P=$P' '
P=$P$BC$FG_CYAN$EC'\w'$BC$FG_OFF$EC
P=$P' '

export PS1='\n'$BC$RESET_ALL$BOLD$EC$P$BC$RESET_ALL$EC
export PS2=$BC$RESET_ALL$CONCEAL$EC$P$BC$RESET_ALL$EC
PS1="$(crush "$PS1")"
PS2="$(crush "$PS2")"

export PROMPT_DIRTRIM=3

echo "${PS1@A}"
echo "${PS2@A}"
echo "${PROMPT_DIRTRIM@A}"
