#!/bin/bash

RESET='\[\e[0m\]'

PS1=''
PS1=$PS1'\[\e[1;32m\]\u'$RESET
PS1=$PS1' '
PS1=$PS1'\[\e[1;33m\]\h'$RESET
PS1=$PS1' '
PS1=$PS1'\[\e[1;36m\]\w'$RESET
PS1=$PS1' '

PROMPT_DIRTRIM=3

export PS1
export PROMPT_DIRTRIM

echo "${PS1@A}"
echo "${PROMPT_DIRTRIM@A}"
