#!/bin/bash

. "${BASH_SOURCE%/*/*}/utils/00-ansi-sgr"

PS_BNP='\['
PS_ENP='\]'

function crush {
    : "$1"
    : "${_//\\\]\\\[}"
    : "${_//m\\e\[/;}"
    echo "$_"
}

P=''
P=$P$PS_BNP$SGR_FG_GREEN$PS_ENP'\u'$PS_BNP$SGR_FG_OFF$PS_ENP
P=$P' '
P=$P$PS_BNP$SGR_FG_CYAN$PS_ENP'\w'$PS_BNP$SGR_FG_OFF$PS_ENP
P=$P' '

export PS1=$PS_BNP$SGR_RESET_ALL$SGR_BOLD$PS_ENP$P$PS_BNP$SGR_RESET_ALL$PS_ENP
export PS2=$PS_BNP$SGR_RESET_ALL$SGR_CONCEAL$PS_ENP$P$PS_BNP$SGR_RESET_ALL$PS_ENP
PS1="$(crush "$PS1")"
PS2="$(crush "$PS2")"

export PROMPT_DIRTRIM=3

echo "${PS1@A}"
# echo "${PS2@A}"
echo "${PROMPT_DIRTRIM@A}"
