#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail
shopt -s globstar
shopt -s shift_verbose
shopt -u sourcepath
[[ $0 != /* ]] &&
	SCRIPT_RELATIVE=TRUE
SCRIPT_PATH=${SCRIPT_RELATIVE:+$PWD/}$0
SCRIPT_DIR=${SCRIPT_PATH%/*}/
